[project]
name = "startinfo"
version = "2.4.3"
description = "一款基于 PySide6 与 QFluentWidgets 开发的桌面信息聚合工具，通过模块化组件在开机后快速展示各类实用信息。"
readme = "README.md"
authors = [
    { name = "HuangTao", email = "Ht2174509658@outlook.com" }
]
requires-python = ">=3.13,<3.14"
dependencies = [
    "httpx>=0.28.1",
    "jinja2>=3.1.6",
    "loguru>=0.7.3",
    "lunar-python>=1.4.8",
    "nuitka>=4.1.3; sys_platform == 'win32'",
    "auto-py-to-exe>=2.50.1; sys_platform == 'darwin'",
    "pyside6>=6.11.2",
    "pyside6-fluent-widgets>=1.11.3",
    "qasync>=0.28.0",
]

[tool.uv]
package = false